### ISSUE TITLE
Asset Precompile fails

### ISSUE THREAD

**Issue by dpcasady** [bertramdev/handlebars-grails-asset-pipeline#2]
After executing `asset-precompile`, I run into an error when trying to process handlebars assets:

    Error running script asset-precompile : java.lang.Exception: 
                Handlebars Engine compilation of handlebars to javascript failed.
                org.mozilla.javascript.EcmaError: ReferenceError: "JSON" is not defined. (handlebars.js#2192)

Everything works fine when handlebars assets are compiled during runtime, and the error is due to the `JSON` global object not being defined in the handlebars.js (2.0) file included with the plugin. I know `JSON` is defined in rhino. After looking into it I'm confident this is due to rhino only being included during runtime and not being included in the build scope.

If I specify `build "org.mozilla:rhino:1.7R4"` in my `BuildConfig.groovy` dependencies, the asset precompile works as expected. Here's the rest of the stacktrace for reference:

	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1002)
	at asset.pipeline.handlebars.HandlebarsProcessor.process(HandlebarsProcessor.groovy:79)
	at asset.pipeline.AbstractAssetFile.processedStream(AbstractAssetFile.groovy:87)
	at asset.pipeline.DirectiveProcessor.fileContents(DirectiveProcessor.groovy:291)
	at asset.pipeline.DirectiveProcessor$fileContents$1.callCurrent(Unknown Source)
	at asset.pipeline.DirectiveProcessor$fileContents$1.callCurrent(Unknown Source)
	at asset.pipeline.DirectiveProcessor.loadContentsForTree(DirectiveProcessor.groovy:122)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at asset.pipeline.DirectiveProcessor.loadContentsForTree(DirectiveProcessor.groovy:117)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at asset.pipeline.DirectiveProcessor.loadContentsForTree(DirectiveProcessor.groovy:117)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at asset.pipeline.DirectiveProcessor.loadContentsForTree(DirectiveProcessor.groovy:117)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at asset.pipeline.DirectiveProcessor.loadContentsForTree(DirectiveProcessor.groovy:117)
	at asset.pipeline.DirectiveProcessor.compile(DirectiveProcessor.groovy:60)
	at asset.pipeline.DirectiveProcessor$compile.call(Unknown Source)
	at asset.pipeline.AssetCompiler.compile(AssetCompiler.groovy:91)
	at asset.pipeline.AssetCompiler$compile.call(Unknown Source)
	at _AssetCompile_groovy$_run_closure2.doCall(_AssetCompile_groovy:78)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at AssetPrecompile.invokeMethod(AssetPrecompile)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at AssetPrecompile$_run_closure1.doCall(AssetPrecompile:10)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at gant.Gant.withBuildListeners(Gant.groovy:427)
	at gant.Gant.this$2$withBuildListeners(Gant.groovy)
	at gant.Gant$this$2$withBuildListeners$0.callCurrent(Unknown Source)
	at gant.Gant.dispatch(Gant.groovy:415)
	at gant.Gant.this$2$dispatch(Gant.groovy)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at gant.Gant.invokeMethod(Gant.groovy)
	at gant.Gant.executeTargets(Gant.groovy:591)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at gant.Gant.executeTargets(Gant.groovy:590)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)

**Comment by davydotcom** [comment]
well thats rather odd. must be a transitive dependency issue it should be getting included. Is something requiring a different version at build time of Rhino Js?
--
David Estes

On February 18, 2015 at 2:37:00 AM, Danny Casady (notifications@github.com) wrote:

After executing asset-precompile, I run into an error when trying to process handlebars assets:

Error running script asset-precompile : java.lang.Exception:  
            Handlebars Engine compilation of handlebars to javascript failed.
            org.mozilla.javascript.EcmaError: ReferenceError: "JSON" is not defined. (handlebars.js#2192)

Everything works fine when handlebars assets are compiled during runtime, and the error is due to the JSON global object not being defined in the handlebars.js (2.0) file included with the plugin. I know JSON is defined in rhino. After looking into it I'm confident this is due to rhino only being included during runtime and not being included in the build scope.

If I specify build "org.mozilla:rhino:1.7R4" in my BuildConfig.groovy dependencies, the asset precompile works as expected. Here's the rest of the stacktrace for reference:

at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1002)
at asset.pipeline.handlebars.HandlebarsProcessor.process(HandlebarsProcessor.groovy:79)
at asset.pipeline.AbstractAssetFile.processedStream(AbstractAssetFile.groovy:87)
at asset.pipeline.DirectiveProcessor.fileContents(DirectiveProcessor.groovy:291)
at asset.pipeline.DirectiveProcessor$fileContents$1.callCurrent(Unknown Source)
at asset.pipeline.DirectiveProcessor$fileContents$1.callCurrent(Unknown Source)
at asset.pipeline.DirectiveProcessor.loadContentsForTree(DirectiveProcessor.groovy:122)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at asset.pipeline.DirectiveProcessor.loadContentsForTree(DirectiveProcessor.groovy:117)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at asset.pipeline.DirectiveProcessor.loadContentsForTree(DirectiveProcessor.groovy:117)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at asset.pipeline.DirectiveProcessor.loadContentsForTree(DirectiveProcessor.groovy:117)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at asset.pipeline.DirectiveProcessor.loadContentsForTree(DirectiveProcessor.groovy:117)
at asset.pipeline.DirectiveProcessor.compile(DirectiveProcessor.groovy:60)
at asset.pipeline.DirectiveProcessor$compile.call(Unknown Source)
at asset.pipeline.AssetCompiler.compile(AssetCompiler.groovy:91)
at asset.pipeline.AssetCompiler$compile.call(Unknown Source)
at _AssetCompile_groovy$_run_closure2.doCall(_AssetCompile_groovy:78)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at AssetPrecompile.invokeMethod(AssetPrecompile)
at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
at AssetPrecompile$_run_closure1.doCall(AssetPrecompile:10)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at gant.Gant.withBuildListeners(Gant.groovy:427)
at gant.Gant.this$2$withBuildListeners(Gant.groovy)
at gant.Gant$this$2$withBuildListeners$0.callCurrent(Unknown Source)
at gant.Gant.dispatch(Gant.groovy:415)
at gant.Gant.this$2$dispatch(Gant.groovy)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at gant.Gant.invokeMethod(Gant.groovy)
at gant.Gant.executeTargets(Gant.groovy:591)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
at gant.Gant.executeTargets(Gant.groovy:590)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)

**Comment by dpcasady** [comment]
I can't find anything else that would be using rhino, but yeah it's weird...after doing a `clean-all` and `refresh-dependencies`, `dependency-report` only shows rhino as a dependency for asset-pipeline under the runtime and test scopes:

    compile - Dependencies placed on the classpath for compilation (total: 132)
    ...
    +--- org.grails.plugins:asset-pipeline:2.1.1
    |    \--- com.bertramlabs.plugins:asset-pipeline-core:2.1.1
    +--- org.grails.plugins:sass-asset-pipeline:2.0.4
    |    \--- com.bertramlabs.plugins:sass-asset-pipeline:2.0.4
    +--- org.grails.plugins:coffee-asset-pipeline:2.0.6
    |    \--- com.bertramlabs.plugins:coffee-asset-pipeline:2.0.6
    +--- org.grails.plugins:handlebars-asset-pipeline:2.0.0.2
    |    \--- com.bertramlabs.plugins:handlebars-asset-pipeline:2.1.2
    ...
    runtime - Dependencies needed at runtime but not for compilation (total: 175)
    ...
    +--- org.grails.plugins:asset-pipeline:2.1.1
    |    \--- org.mozilla:rhino:1.7R4
    |    \--- com.bertramlabs.plugins:asset-pipeline-core:2.1.1
    |         \--- com.google.javascript:closure-compiler:v20141023
    |              \--- com.google.javascript:closure-compiler-externs:v20141023
    |              \--- args4j:args4j:2.0.26
    |              \--- com.google.protobuf:protobuf-java:2.5.0
    |              \--- com.google.code.findbugs:jsr305:1.3.9
    +--- org.grails.plugins:sass-asset-pipeline:2.0.4
    |    \--- com.bertramlabs.plugins:sass-asset-pipeline:2.0.4
    |         \--- org.jruby:jruby-complete:1.7.11
    |         \--- com.bertramlabs.plugins:jruby-container:0.3.0
    +--- org.grails.plugins:coffee-asset-pipeline:2.0.6
    |    \--- com.bertramlabs.plugins:coffee-asset-pipeline:2.0.6
    |         \--- org.codehaus.groovy:groovy:2.3.7
    +--- org.grails.plugins:handlebars-asset-pipeline:2.0.0.2
    |    \--- com.bertramlabs.plugins:handlebars-asset-pipeline:2.1.2
    ...
    test - Dependencies needed for test compilation and execution but not at runtime (total: 208)
    ...
    +--- org.grails.plugins:asset-pipeline:2.1.1
    |    \--- org.mozilla:rhino:1.7R4
    |    \--- com.bertramlabs.plugins:asset-pipeline-core:2.1.1
    |         \--- com.google.javascript:closure-compiler:v20141023
    |              \--- com.google.javascript:closure-compiler-externs:v20141023
    |              \--- args4j:args4j:2.0.26
    |              \--- com.google.protobuf:protobuf-java:2.5.0
    |              \--- com.google.code.findbugs:jsr305:1.3.9
    +--- org.grails.plugins:sass-asset-pipeline:2.0.4
    |    \--- com.bertramlabs.plugins:sass-asset-pipeline:2.0.4
    |         \--- org.jruby:jruby-complete:1.7.11
    |         \--- com.bertramlabs.plugins:jruby-container:0.3.0
    +--- org.grails.plugins:coffee-asset-pipeline:2.0.6
    |    \--- com.bertramlabs.plugins:coffee-asset-pipeline:2.0.6
    |         \--- org.codehaus.groovy:groovy:2.3.7
    +--- org.grails.plugins:handlebars-asset-pipeline:2.0.0.2
    |    \--- com.bertramlabs.plugins:handlebars-asset-pipeline:2.1.2
    ...

**Comment by davydotcom** [comment]
Should be fixed in `2.5.1`
